name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SWIFT_VERSION: "6.2.4"
  SWIFTLINT_VERSION: 0.63.3

jobs:
  lint:
    name: Lint All Source Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Lint All Source Files using SwiftLint (Strict)
        uses: stanfordbdhg/action-swiftlint@234b29234afef1ae74ee94b915c41484bddb7f17 # v4.1.2
        with:
          version: ${{ env.SWIFTLINT_VERSION }}
          args: --strict

  build_test_macos:
    name: Build and Test (macOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Swift Tools
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test --skip-build

  build_test_linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Swift Tools
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build
        run: swift build --build-tests

      - name: Test
        run: swift test --skip-build

  build_with_static_linux_sdk:
    name: Build with Static Linux SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Swift + Static Linux SDK
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 # v1.14.0
        with:
          sdks: static-linux
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build
        run: swift build --swift-sdk x86_64-swift-linux-musl
